# Generated by Django 5.0.1 on 2026-02-12 02:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0006_alter_apontamentofuncionario_unique_together'),
        ('obras', '0004_alter_obra_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducaoDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('clima', models.CharField(choices=[('sol', 'Sol'), ('chuva', 'Chuva'), ('nublado', 'Nublado')], default='sol', max_length=10, verbose_name='Clima/Tempo')),
                ('houve_ociosidade', models.BooleanField(default=False, verbose_name='Houve Ociosidade')),
                ('houve_retrabalho', models.BooleanField(default=False, verbose_name='Houve Retrabalho')),
                ('motivo_retrabalho', models.TextField(blank=True, default='', verbose_name='Motivo do Retrabalho')),
                ('metragem_executada', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Metragem Executada (m²)')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('etapa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producoes_diarias', to='obras.etapa', verbose_name='Etapa')),
                ('funcionario', models.ForeignKey(limit_choices_to={'funcao': 'pedreiro'}, on_delete=django.db.models.deletion.PROTECT, related_name='producoes_diarias', to='funcionarios.funcionario', verbose_name='Pedreiro')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producoes_diarias', to='obras.obra', verbose_name='Obra')),
            ],
            options={
                'verbose_name': 'Produção Diária',
                'verbose_name_plural': 'Produções Diárias',
                'ordering': ['-data', 'funcionario__nome_completo'],
                'unique_together': {('funcionario', 'obra', 'etapa', 'data')},
            },
        ),
    ]
