# Generated by Django 5.0.1 on 2026-02-12 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProducaoDiaria',
        ),
    ]
