# Generated by Django 5.0.1 on 2026-02-22 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAreaPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('obras', 'Obras'), ('funcionarios', 'Funcionários'), ('funcionarios_apontamentos', 'Funcionários - Apontamentos'), ('funcionarios_fechamentos', 'Funcionários - Fechamentos'), ('ferramentas', 'Ferramentas'), ('analytics', 'Analytics'), ('relatorios', 'Relatórios'), ('clientes', 'Clientes')], max_length=64, verbose_name='Área')),
                ('can_view', models.BooleanField(default=False, verbose_name='Ver')),
                ('can_create', models.BooleanField(default=False, verbose_name='Criar')),
                ('can_edit', models.BooleanField(default=False, verbose_name='Editar')),
                ('can_delete', models.BooleanField(default=False, verbose_name='Excluir')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_permissions', to='auth.group', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Permissão do Grupo por Área',
                'verbose_name_plural': 'Permissões dos Grupos por Área',
                'ordering': ('group__name', 'area'),
                'unique_together': {('group', 'area')},
            },
        ),
    ]
