# Generated by Django 5.0.1 on 2026-02-22 15:12

from django.db import migrations


def adjust_group_profiles(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    GroupAreaPermission = apps.get_model('configuracoes', 'GroupAreaPermission')

    all_areas = [
        'obras',
        'funcionarios',
        'funcionarios_apontamentos',
        'funcionarios_fechamentos',
        'ferramentas',
        'analytics',
        'relatorios',
        'clientes',
    ]

    profiles = {
        'Obras': {
            'obras': {'view': True, 'create': True, 'edit': True, 'delete': True},
        },
        'Funcionários': {
            'funcionarios': {'view': True, 'create': True, 'edit': True, 'delete': True},
            'funcionarios_apontamentos': {'view': True, 'create': True, 'edit': True, 'delete': True},
            'funcionarios_fechamentos': {'view': True, 'create': True, 'edit': True, 'delete': True},
        },
        'Ferramentas': {
            'ferramentas': {'view': True, 'create': True, 'edit': True, 'delete': True},
        },
        'Analytics': {
            'analytics': {'view': True, 'create': False, 'edit': False, 'delete': False},
        },
        'Relatórios': {
            'relatorios': {'view': True, 'create': False, 'edit': False, 'delete': False},
        },
        'Clientes': {
            'clientes': {'view': True, 'create': True, 'edit': True, 'delete': True},
        },
    }

    for group_name, area_cfg in profiles.items():
        group, _ = Group.objects.get_or_create(name=group_name)
        for area in all_areas:
            cfg = area_cfg.get(area, {'view': False, 'create': False, 'edit': False, 'delete': False})
            perm, _ = GroupAreaPermission.objects.get_or_create(group=group, area=area)
            perm.can_view = cfg['view']
            perm.can_create = cfg['create']
            perm.can_edit = cfg['edit']
            perm.can_delete = cfg['delete']
            perm.save()


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0002_seed_default_groups'),
    ]

    operations = [
        migrations.RunPython(adjust_group_profiles, noop_reverse),
    ]

