# Generated by Django 5.0.1 on 2026-03-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0003_adjust_group_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupareapermission',
            name='area',
            field=models.CharField(choices=[('obras', 'Obras'), ('funcionarios', 'Funcionários'), ('funcionarios_apontamentos', 'Funcionários - Apontamentos'), ('funcionarios_fechamentos', 'Funcionários - Fechamentos'), ('ferramentas', 'Ferramentas'), ('analytics', 'Analytics'), ('relatorios', 'Relatórios'), ('clientes', 'Clientes'), ('fornecedores', 'Fornecedores')], max_length=64, verbose_name='Área'),
        ),
    ]
