# Generated by Django 5.0.1 on 2026-02-10 20:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def remove_duplicate_apontamentos(apps, schema_editor):
    """Remove duplicatas (funcionario, data) mantendo o registro com maior valor_diaria."""
    ApontamentoFuncionario = apps.get_model('funcionarios', 'ApontamentoFuncionario')
    from django.db.models import Count
    
    duplicates = (
        ApontamentoFuncionario.objects
        .values('funcionario_id', 'data')
        .annotate(cnt=Count('id'))
        .filter(cnt__gt=1)
    )
    
    for dup in duplicates:
        aps = ApontamentoFuncionario.objects.filter(
            funcionario_id=dup['funcionario_id'],
            data=dup['data']
        ).order_by('-valor_diaria', '-id')
        # Keep first (highest value), delete rest
        ids_to_delete = list(aps.values_list('id', flat=True)[1:])
        ApontamentoFuncionario.objects.filter(id__in=ids_to_delete).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
        ('obras', '0004_alter_obra_cliente'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_apontamentos, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='apontamentofuncionario',
            unique_together={('funcionario', 'data')},
        ),
        migrations.AddField(
            model_name='apontamentofuncionario',
            name='clima',
            field=models.CharField(choices=[('sol', 'Sol'), ('chuva', 'Chuva'), ('nublado', 'Nublado')], default='sol', max_length=10, verbose_name='Clima'),
        ),
        migrations.AddField(
            model_name='apontamentofuncionario',
            name='etapa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apontamentos', to='obras.etapa', verbose_name='Etapa/Fase'),
        ),
        migrations.AddField(
            model_name='apontamentofuncionario',
            name='horas_trabalhadas',
            field=models.DecimalField(decimal_places=1, default=Decimal('8.0'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.5')), django.core.validators.MaxValueValidator(Decimal('24.0'))], verbose_name='Horas Trabalhadas'),
        ),
        migrations.AddField(
            model_name='apontamentofuncionario',
            name='houve_ociosidade',
            field=models.BooleanField(default=False, verbose_name='Houve Ociosidade'),
        ),
        migrations.AddField(
            model_name='apontamentofuncionario',
            name='houve_retrabalho',
            field=models.BooleanField(default=False, verbose_name='Houve Retrabalho'),
        ),
        migrations.AddField(
            model_name='apontamentofuncionario',
            name='motivo_retrabalho',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo do Retrabalho'),
        ),
        migrations.AddField(
            model_name='apontamentofuncionario',
            name='observacao_ociosidade',
            field=models.TextField(blank=True, null=True, verbose_name='Justificativa da Ociosidade'),
        ),
        migrations.AddField(
            model_name='fechamentosemanal',
            name='dias_ociosidade',
            field=models.PositiveIntegerField(default=0, verbose_name='Dias com Ociosidade'),
        ),
        migrations.AddField(
            model_name='fechamentosemanal',
            name='dias_retrabalho',
            field=models.PositiveIntegerField(default=0, verbose_name='Dias com Retrabalho'),
        ),
        migrations.AddField(
            model_name='fechamentosemanal',
            name='total_horas',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=6, verbose_name='Total de Horas'),
        ),
    ]
