# Generated by Django 5.0.1 on 2026-02-10 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_alter_apontamentofuncionario_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechamentosemanal',
            name='status',
            field=models.CharField(choices=[('fechado', 'Fechado'), ('pago', 'Pago')], default='fechado', max_length=10, verbose_name='Status'),
        ),
    ]
