# Generated by Django 5.0.1 on 2026-02-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='theme_variant',
            field=models.CharField(choices=[('default', 'Padrão'), ('soft', 'Suave'), ('gray', 'Cinza'), ('blue', 'Azulado')], default='default', max_length=20),
        ),
    ]
