# Generated by Django 5.0.1 on 2026-02-11 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0005_userprofile_theme_variant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='apontamentofuncionario',
            unique_together=set(),
        ),
    ]
