# Generated by Django 5.0.1 on 2026-02-12 02:31

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0006_alter_apontamentofuncionario_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='apontamentofuncionario',
            name='metragem_executada',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Metragem Executada (m²)'),
        ),
    ]
