# Generated by Django 5.0.1 on 2026-02-18 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0010_remove_unique_together_permitir_multiplos_apontamentos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apontamentofuncionario',
            options={'ordering': ['-data', '-created_at'], 'verbose_name': 'Apontamento de Funcionário', 'verbose_name_plural': 'Apontamentos de Funcionários'},
        ),
    ]
