# Generated by Django 5.0.1 on 2026-02-18 18:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0011_alter_apontamentofuncionario_options'),
        ('obras', '0009_etapa1_novos_campos_etapa2_platibanda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApontamentoDiarioLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('producao_total', models.DecimalField(decimal_places=2, help_text='Total produzido pela equipe (blocos, m², %, etc)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Produção Total')),
                ('unidade_medida', models.CharField(choices=[('blocos', 'Blocos'), ('m2', 'Metros Quadrados (m²)'), ('percentual', 'Percentual (%)')], max_length=20, verbose_name='Unidade de Medida')),
                ('clima', models.CharField(choices=[('sol', 'Sol'), ('chuva', 'Chuva'), ('nublado', 'Nublado')], default='sol', max_length=10, verbose_name='Clima')),
                ('houve_ociosidade', models.BooleanField(default=False, verbose_name='Houve Ociosidade')),
                ('observacao_ociosidade', models.TextField(blank=True, null=True, verbose_name='Observação Ociosidade')),
                ('houve_retrabalho', models.BooleanField(default=False, verbose_name='Houve Retrabalho')),
                ('motivo_retrabalho', models.TextField(blank=True, null=True, verbose_name='Motivo Retrabalho')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('etapa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='obras.etapa', verbose_name='Etapa')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apontamentos_lote', to='obras.obra', verbose_name='Obra')),
            ],
            options={
                'verbose_name': 'Apontamento Diário em Lote',
                'verbose_name_plural': 'Apontamentos Diários em Lote',
                'ordering': ['-data', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FuncionarioLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_trabalhadas', models.DecimalField(decimal_places=1, default=Decimal('8.0'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.5')), django.core.validators.MaxValueValidator(Decimal('24.0'))], verbose_name='Horas Trabalhadas')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='funcionarios.funcionario', verbose_name='Funcionário')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='funcionarios.apontamentodiariolote', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Funcionário do Lote',
                'verbose_name_plural': 'Funcionários do Lote',
                'unique_together': {('lote', 'funcionario')},
            },
        ),
    ]
