# Generated by Django 5.0.1 on 2026-02-18 18:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0012_apontamentodiariolote_funcionariolote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apontamentodiariolote',
            name='producao_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Total produzido pela equipe (blocos, m², %, etc)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Produção Total'),
        ),
        migrations.AlterField(
            model_name='apontamentodiariolote',
            name='unidade_medida',
            field=models.CharField(blank=True, choices=[('blocos', 'Blocos'), ('m2', 'Metros Quadrados (m²)'), ('percentual', 'Percentual (%)')], default='blocos', max_length=20, verbose_name='Unidade de Medida'),
        ),
    ]
