# Generated by Django 5.0.1 on 2026-02-18 19:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0013_alter_apontamentodiariolote_producao_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apontamentodiariolote',
            name='producao_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total produzido pela equipe (blocos, m², %, etc)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Produção Total'),
        ),
    ]
