# Generated by Django 5.0.1 on 2026-02-18 23:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0014_alter_apontamentodiariolote_producao_total'),
        ('obras', '0010_etapa1fundacao_parede_7fiadas_blocos'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('indicador', models.CharField(choices=[('alicerce_percentual', 'Levantar Alicerce (%)'), ('parede_7fiadas', 'Parede até 7 Fiadas (blocos)'), ('respaldo_conclusao', 'Respaldo - Conclusão (%)'), ('laje_conclusao', 'Laje - Conclusão (%)'), ('platibanda', 'Platibanda (metros lineares)'), ('cobertura_conclusao', 'Cobertura - Conclusão (%)'), ('reboco_externo', 'Reboco Externo (m²)'), ('reboco_interno', 'Reboco Interno (m²)')], max_length=30, verbose_name='Indicador')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Quantidade Produzida')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('etapa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_producao', to='obras.etapa', verbose_name='Etapa')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_producao', to='funcionarios.funcionario', verbose_name='Funcionário')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_producao', to='obras.obra', verbose_name='Obra')),
            ],
            options={
                'verbose_name': 'Registro de Produção',
                'verbose_name_plural': 'Registros de Produção',
                'ordering': ['-data', 'funcionario__nome_completo'],
                'indexes': [models.Index(fields=['funcionario', 'data'], name='funcionario_funcion_3912a8_idx'), models.Index(fields=['obra', 'indicador'], name='funcionario_obra_id_6c3a83_idx'), models.Index(fields=['data', 'indicador'], name='funcionario_data_99e4e5_idx')],
                'unique_together': {('funcionario', 'data', 'obra', 'indicador')},
            },
        ),
    ]
