# Generated by Django 5.2.5 on 2026-02-20 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0015_registroproducao'),
        ('obras', '0010_etapa1fundacao_parede_7fiadas_blocos'),
    ]

    operations = [
        migrations.AddField(
            model_name='apontamentodiariolote',
            name='possui_placa',
            field=models.BooleanField(default=False, help_text='Marque se a obra possui placa de identificação', verbose_name='Possui Placa'),
        ),
        migrations.AddField(
            model_name='apontamentofuncionario',
            name='possui_placa',
            field=models.BooleanField(default=False, help_text='Marque se a obra possui placa de identificação', verbose_name='Possui Placa'),
        ),
        migrations.CreateModel(
            name='FotoApontamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='apontamentos/fotos/%Y/%m/', verbose_name='Foto')),
                ('descricao', models.CharField(blank=True, help_text='Descrição opcional da foto', max_length=200, null=True, verbose_name='Descrição')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data do Upload')),
                ('apontamento_individual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='funcionarios.apontamentofuncionario', verbose_name='Apontamento Individual')),
                ('apontamento_lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='funcionarios.apontamentodiariolote', verbose_name='Apontamento em Lote')),
                ('obra', models.ForeignKey(help_text='Facilita buscar todas as fotos de uma obra', on_delete=django.db.models.deletion.CASCADE, related_name='fotos_apontamentos', to='obras.obra', verbose_name='Obra')),
            ],
            options={
                'verbose_name': 'Foto do Apontamento',
                'verbose_name_plural': 'Fotos dos Apontamentos',
                'ordering': ['-data_upload'],
            },
        ),
    ]
