# Generated by Django 5.0.1 on 2026-02-20 23:35

import apps.funcionarios.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0016_apontamentodiariolote_possui_placa_and_more'),
        ('obras', '0011_alter_etapa1fundacao_levantar_alicerce_percentual'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotoapontamento',
            name='data_foto',
            field=models.DateField(blank=True, help_text='Data do apontamento ao qual a foto pertence', null=True, verbose_name='Data da Foto'),
        ),
        migrations.AddField(
            model_name='fotoapontamento',
            name='etapa',
            field=models.ForeignKey(blank=True, help_text='Etapa em que a foto foi tirada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotos', to='obras.etapa', verbose_name='Etapa'),
        ),
        migrations.AlterField(
            model_name='fotoapontamento',
            name='foto',
            field=models.ImageField(upload_to=apps.funcionarios.models.foto_apontamento_upload_path, verbose_name='Foto'),
        ),
    ]
