# Generated by Django 5.0.1 on 2026-02-21 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0017_foto_etapa_data_foto'),
        ('obras', '0011_alter_etapa1fundacao_levantar_alicerce_percentual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoAlteracaoEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alteracao', models.CharField(choices=[('criacao', 'Criação'), ('edicao', 'Edição'), ('exclusao', 'Exclusão')], max_length=20, verbose_name='Tipo de Alteração')),
                ('data_referencia', models.DateField(help_text='Data do apontamento que foi alterado/excluído', verbose_name='Data de Referência')),
                ('descricao', models.TextField(help_text='Detalhes da alteração', verbose_name='Descrição')),
                ('dados_anteriores', models.JSONField(blank=True, help_text='Estado antes da alteração', null=True, verbose_name='Dados Anteriores')),
                ('dados_novos', models.JSONField(blank=True, help_text='Estado depois da alteração', null=True, verbose_name='Dados Novos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora da Alteração')),
                ('etapa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_alteracoes', to='obras.etapa', verbose_name='Etapa')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_alteracoes', to='obras.obra', verbose_name='Obra')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Histórico de Alteração',
                'verbose_name_plural': 'Histórico de Alterações',
                'ordering': ['-created_at'],
            },
        ),
    ]
