# Generated by Django 5.0.1 on 2026-02-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0018_historicoalteracaoetapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cargo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='endereco',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
