# Generated by Django 5.0.1 on 2026-03-08 15:25

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0021_alter_funcionario_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='funcao',
            field=models.CharField(choices=[('pedreiro', 'Pedreiro'), ('servente', 'Servente'), ('fiscal', 'Fiscal')], max_length=10, verbose_name='Função'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='valor_diaria',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor da Diária (R$)'),
        ),
    ]
