# Generated by Django 5.0.1 on 2026-03-08 15:35

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0022_alter_funcionario_funcao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apontamentofuncionario',
            name='horas_trabalhadas',
            field=models.DecimalField(decimal_places=1, default=Decimal('8.0'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('24.0'))], verbose_name='Horas Trabalhadas'),
        ),
        migrations.AlterField(
            model_name='funcionariolote',
            name='horas_trabalhadas',
            field=models.DecimalField(decimal_places=1, default=Decimal('8.0'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('24.0'))], verbose_name='Horas Trabalhadas'),
        ),
    ]
