# Generated by Django 5.0.1 on 2026-03-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0023_alter_apontamentofuncionario_horas_trabalhadas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='funcao',
            field=models.CharField(choices=[('pedreiro', 'Pedreiro'), ('servente', 'Servente'), ('fiscal', 'Fiscal'), ('pintor', 'Pintor'), ('soldador', 'Soldador'), ('eletricista', 'Eletricista'), ('encanador', 'Encanador')], max_length=15, verbose_name='Função'),
        ),
    ]
