# Generated by Django 5.0.1 on 2026-02-28 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, help_text='Somente números ou formatado (000.000.000-00)', max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$|^\\d{11}$', 'CPF inválido')], verbose_name='CPF'),
        ),
    ]
