# Generated by Django 5.0.1 on 2026-02-10 00:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_etapa', models.IntegerField(choices=[(1, 'Etapa 1 - Fundação (29.9%)'), (2, 'Etapa 2 - Estrutura (45%)'), (3, 'Etapa 3 - Revestimentos e Instalações (70%)'), (4, 'Etapa 4 - Acabamentos (84%)'), (5, 'Etapa 5 - Finalização (95%)')], verbose_name='Número da Etapa')),
                ('percentual_valor', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentual da Etapa')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('data_termino', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('concluida', models.BooleanField(default=False, verbose_name='Concluída')),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
                'ordering': ['numero_etapa'],
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Obra')),
                ('endereco', models.TextField(verbose_name='Endereço')),
                ('cliente', models.CharField(max_length=200, verbose_name='Cliente')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_previsao_termino', models.DateField(blank=True, null=True, verbose_name='Previsão de Término')),
                ('status', models.CharField(choices=[('planejamento', 'Planejamento'), ('em_andamento', 'Em Andamento'), ('pausada', 'Pausada'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='planejamento', max_length=20, verbose_name='Status')),
                ('percentual_concluido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentual Concluído (%)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Etapa1Fundacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limpeza_terreno', models.BooleanField(default=False, verbose_name='Limpeza do Terreno')),
                ('instalacao_energia_agua', models.BooleanField(default=False, verbose_name='Instalação de Energia e Água')),
                ('marcacao_escavacao_dias', models.PositiveIntegerField(default=0, verbose_name='Marcação e Escavação (dias)')),
                ('locacao_ferragem_dias', models.PositiveIntegerField(default=0, verbose_name='Locação de Ferragem (dias)')),
                ('alicerce_percentual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Alicerce, Reboco e Impermeabilização (%)')),
                ('aterro_contrapiso_dias', models.PositiveIntegerField(default=0, verbose_name='Aterro e Contrapiso (dias)')),
                ('parede_7fiadas_blocos', models.PositiveIntegerField(default=0, verbose_name='Parede 7 Fiadas (blocos)')),
                ('fiadas_respaldo_dias', models.PositiveIntegerField(default=0, verbose_name='8 Fiadas até Respaldo (dias)')),
                ('etapa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fundacao', to='obras.etapa', verbose_name='Etapa')),
            ],
            options={
                'verbose_name': 'Etapa 1 - Fundação',
                'verbose_name_plural': 'Etapas 1 - Fundação',
            },
        ),
        migrations.CreateModel(
            name='Etapa2Estrutura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montagem_laje_dias', models.PositiveIntegerField(default=0, verbose_name='Montagem da Laje (dias)')),
                ('platibanda_blocos', models.PositiveIntegerField(default=0, verbose_name='Platibanda (blocos)')),
                ('cobertura_dias', models.PositiveIntegerField(default=0, verbose_name='Cobertura Completa (dias)')),
                ('etapa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estrutura', to='obras.etapa', verbose_name='Etapa')),
            ],
            options={
                'verbose_name': 'Etapa 2 - Estrutura',
                'verbose_name_plural': 'Etapas 2 - Estrutura',
            },
        ),
        migrations.CreateModel(
            name='Etapa3Instalacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reboco_externo_m2', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Reboco Externo (m²)')),
                ('reboco_interno_m2', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Reboco Interno (m²)')),
                ('instalacao_portais', models.BooleanField(default=False, verbose_name='Instalação de Portais')),
                ('agua_fria', models.BooleanField(default=False, verbose_name='Água Fria')),
                ('esgoto', models.BooleanField(default=False, verbose_name='Esgoto')),
                ('fluvial', models.BooleanField(default=False, verbose_name='Fluvial')),
                ('etapa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instalacoes', to='obras.etapa', verbose_name='Etapa')),
            ],
            options={
                'verbose_name': 'Etapa 3 - Instalações',
                'verbose_name_plural': 'Etapas 3 - Instalações',
            },
        ),
        migrations.CreateModel(
            name='Etapa4Acabamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portas_janelas', models.BooleanField(default=False, verbose_name='Portas e Janelas')),
                ('pintura_externa_1demao_dias', models.PositiveIntegerField(default=0, verbose_name='Pintura Externa 1ª Demão (dias)')),
                ('pintura_interna_1demao_dias', models.PositiveIntegerField(default=0, verbose_name='Pintura Interna 1ª Demão (dias)')),
                ('assentamento_piso_dias', models.PositiveIntegerField(default=0, verbose_name='Assentamento de Piso (dias)')),
                ('etapa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acabamentos', to='obras.etapa', verbose_name='Etapa')),
            ],
            options={
                'verbose_name': 'Etapa 4 - Acabamentos',
                'verbose_name_plural': 'Etapas 4 - Acabamentos',
            },
        ),
        migrations.CreateModel(
            name='Etapa5Finalizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pintura_externa_2demao_dias', models.PositiveIntegerField(default=0, verbose_name='Pintura Externa 2ª Demão (dias)')),
                ('pintura_interna_2demao_dias', models.PositiveIntegerField(default=0, verbose_name='Pintura Interna 2ª Demão (dias)')),
                ('loucas_metais', models.BooleanField(default=False, verbose_name='Louças e Metais')),
                ('eletrica', models.BooleanField(default=False, verbose_name='Elétrica')),
                ('etapa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finalizacao', to='obras.etapa', verbose_name='Etapa')),
            ],
            options={
                'verbose_name': 'Etapa 5 - Finalização',
                'verbose_name_plural': 'Etapas 5 - Finalização',
            },
        ),
        migrations.AddField(
            model_name='etapa',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='obras.obra', verbose_name='Obra'),
        ),
        migrations.AlterUniqueTogether(
            name='etapa',
            unique_together={('obra', 'numero_etapa')},
        ),
    ]
