# Generated by Django 5.0.1 on 2026-02-10 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('obras', '0003_convert_cliente_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente', verbose_name='Cliente'),
        ),
    ]
