# Generated by Django 5.0.1 on 2026-02-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0004_alter_obra_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
