# Generated by Django 5.0.1 on 2026-02-15 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0005_obra_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapa1fundacao',
            name='alicerce_percentual',
        ),
        migrations.RemoveField(
            model_name='etapa1fundacao',
            name='aterro_contrapiso_dias',
        ),
        migrations.RemoveField(
            model_name='etapa1fundacao',
            name='fiadas_respaldo_dias',
        ),
        migrations.RemoveField(
            model_name='etapa1fundacao',
            name='locacao_ferragem_dias',
        ),
        migrations.RemoveField(
            model_name='etapa1fundacao',
            name='marcacao_escavacao_dias',
        ),
        migrations.RemoveField(
            model_name='etapa1fundacao',
            name='parede_7fiadas_blocos',
        ),
        migrations.RemoveField(
            model_name='etapa2estrutura',
            name='cobertura_dias',
        ),
        migrations.RemoveField(
            model_name='etapa2estrutura',
            name='montagem_laje_dias',
        ),
        migrations.RemoveField(
            model_name='etapa2estrutura',
            name='platibanda_blocos',
        ),
        migrations.RemoveField(
            model_name='etapa4acabamentos',
            name='assentamento_piso_dias',
        ),
        migrations.RemoveField(
            model_name='etapa4acabamentos',
            name='pintura_externa_1demao_dias',
        ),
        migrations.RemoveField(
            model_name='etapa4acabamentos',
            name='pintura_interna_1demao_dias',
        ),
        migrations.RemoveField(
            model_name='etapa5finalizacao',
            name='pintura_externa_2demao_dias',
        ),
        migrations.RemoveField(
            model_name='etapa5finalizacao',
            name='pintura_interna_2demao_dias',
        ),
        migrations.AddField(
            model_name='etapa1fundacao',
            name='aterro_contrapiso_conclusao',
            field=models.DateField(blank=True, null=True, verbose_name='Aterro e Contrapiso (conclusão)'),
        ),
        migrations.AddField(
            model_name='etapa1fundacao',
            name='fiadas_respaldo_conclusao',
            field=models.DateField(blank=True, null=True, verbose_name='8 Fiadas até Respaldo (conclusão)'),
        ),
        migrations.AddField(
            model_name='etapa1fundacao',
            name='locacao_ferragem_conclusao',
            field=models.DateField(blank=True, null=True, verbose_name='Locação de Ferragem (conclusão)'),
        ),
        migrations.AddField(
            model_name='etapa1fundacao',
            name='marcacao_escavacao_conclusao',
            field=models.DateField(blank=True, null=True, verbose_name='Marcação e Escavação (conclusão)'),
        ),
        migrations.AddField(
            model_name='etapa2estrutura',
            name='cobertura_conclusao',
            field=models.DateField(blank=True, null=True, verbose_name='Cobertura Completa (conclusão)'),
        ),
        migrations.AddField(
            model_name='etapa2estrutura',
            name='montagem_laje_conclusao',
            field=models.DateField(blank=True, null=True, verbose_name='Montagem da Laje (conclusão)'),
        ),
        migrations.AddField(
            model_name='etapa4acabamentos',
            name='assentamento_piso_conclusao',
            field=models.DateField(blank=True, null=True, verbose_name='Assentamento de Piso (conclusão)'),
        ),
        migrations.AddField(
            model_name='etapa4acabamentos',
            name='pintura_externa_1demao_conclusao',
            field=models.DateField(blank=True, null=True, verbose_name='Pintura Externa 1ª Demão (conclusão)'),
        ),
        migrations.AddField(
            model_name='etapa4acabamentos',
            name='pintura_interna_1demao_conclusao',
            field=models.DateField(blank=True, null=True, verbose_name='Pintura Interna 1ª Demão (conclusão)'),
        ),
        migrations.AddField(
            model_name='etapa5finalizacao',
            name='pintura_externa_2demao_conclusao',
            field=models.DateField(blank=True, null=True, verbose_name='Pintura Externa 2ª Demão (conclusão)'),
        ),
        migrations.AddField(
            model_name='etapa5finalizacao',
            name='pintura_interna_2demao_conclusao',
            field=models.DateField(blank=True, null=True, verbose_name='Pintura Interna 2ª Demão (conclusão)'),
        ),
    ]
