# Generated by Django 5.0.1 on 2026-02-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0006_remove_etapa1fundacao_alicerce_percentual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluída')], default='pendente', max_length=20, verbose_name='Status'),
        ),
    ]
