# Generated by Django 5.0.1 on 2026-02-15 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0007_etapa_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapaHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('origem', models.CharField(max_length=120, verbose_name='Origem da Alteração')),
                ('descricao', models.TextField(verbose_name='Descrição da Alteração')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='obras.etapa', verbose_name='Etapa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_etapa', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Histórico de Etapa',
                'verbose_name_plural': 'Históricos de Etapa',
                'ordering': ['-data_hora'],
            },
        ),
    ]
