# Generated by Django 5.0.1 on 2026-02-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0009_etapa1_novos_campos_etapa2_platibanda'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa1fundacao',
            name='parede_7fiadas_blocos',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade de blocos assentados (acumulado)', verbose_name='Parede - 7 Fiadas (blocos)'),
        ),
    ]
