# Generated by Django 5.2.5 on 2026-02-20 14:38

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0010_etapa1fundacao_parede_7fiadas_blocos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapa1fundacao',
            name='levantar_alicerce_percentual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentual de conclusão do levantamento do alicerce', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Levantar Alicerce, Reboco e Impermeabilizar (%)'),
        ),
    ]
