# Generated by Django 5.0.1 on 2026-03-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0011_alter_etapa1fundacao_levantar_alicerce_percentual'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa1fundacao',
            name='aterro_contrapiso_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Aterro e Contrapiso (início)'),
        ),
        migrations.AddField(
            model_name='etapa1fundacao',
            name='fiadas_respaldo_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='8 Fiadas até Respaldo (início)'),
        ),
        migrations.AddField(
            model_name='etapa1fundacao',
            name='locacao_ferragem_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Locação de Ferragem (início)'),
        ),
        migrations.AddField(
            model_name='etapa1fundacao',
            name='marcacao_escavacao_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Marcação e Escavação (início)'),
        ),
        migrations.AddField(
            model_name='etapa2estrutura',
            name='cobertura_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Cobertura Completa (início)'),
        ),
        migrations.AddField(
            model_name='etapa2estrutura',
            name='montagem_laje_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Montagem da Laje (início)'),
        ),
        migrations.AddField(
            model_name='etapa4acabamentos',
            name='assentamento_piso_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Assentamento de Piso (início)'),
        ),
        migrations.AddField(
            model_name='etapa4acabamentos',
            name='pintura_externa_1demao_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Pintura Externa 1ª Demão (início)'),
        ),
        migrations.AddField(
            model_name='etapa4acabamentos',
            name='pintura_interna_1demao_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Pintura Interna 1ª Demão (início)'),
        ),
        migrations.AddField(
            model_name='etapa5finalizacao',
            name='pintura_externa_2demao_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Pintura Externa 2ª Demão (início)'),
        ),
        migrations.AddField(
            model_name='etapa5finalizacao',
            name='pintura_interna_2demao_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Pintura Interna 2ª Demão (início)'),
        ),
    ]
