# Generated by Django 5.0.1 on 2026-02-10 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroFiscalizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_fiscalizacao', models.DateField(verbose_name='Data da Fiscalização')),
                ('clima', models.CharField(choices=[('sol', 'Sol'), ('chuva', 'Chuva'), ('nublado', 'Nublado')], max_length=10, verbose_name='Clima')),
                ('lixo', models.CharField(choices=[('nao_ha', 'Não há'), ('pouco', 'Pouco'), ('muito', 'Muito')], default='nao_ha', max_length=10, verbose_name='Lixo na Obra')),
                ('placa_instalada', models.BooleanField(default=False, verbose_name='Placa Instalada')),
                ('houve_ociosidade', models.BooleanField(default=False, verbose_name='Houve Ociosidade')),
                ('observacao_ociosidade', models.TextField(blank=True, null=True, verbose_name='Observação sobre Ociosidade')),
                ('houve_retrabalho', models.BooleanField(default=False, verbose_name='Houve Retrabalho')),
                ('motivo_retrabalho', models.TextField(blank=True, null=True, verbose_name='Motivo do Retrabalho')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações Gerais')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('fiscal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscalizacoes', to=settings.AUTH_USER_MODEL, verbose_name='Fiscal')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscalizacoes', to='obras.obra', verbose_name='Obra')),
            ],
            options={
                'verbose_name': 'Registro de Fiscalização',
                'verbose_name_plural': 'Registros de Fiscalização',
                'ordering': ['-data_fiscalizacao', '-created_at'],
                'unique_together': {('obra', 'data_fiscalizacao')},
            },
        ),
        migrations.CreateModel(
            name='FotoFiscalizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='fiscalizacao/%Y/%m/%d/', verbose_name='Foto')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('fiscalizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='fiscalizacao.registrofiscalizacao', verbose_name='Fiscalização')),
            ],
            options={
                'verbose_name': 'Foto de Fiscalização',
                'verbose_name_plural': 'Fotos de Fiscalização',
                'ordering': ['ordem', 'uploaded_at'],
            },
        ),
    ]
