# Generated by Django 5.0.1 on 2026-02-10 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizacao', '0002_alter_data_fiscalizacao'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registrofiscalizacao',
            unique_together=set(),
        ),
    ]
