# Generated by Django 5.0.1 on 2026-02-10 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenciaFerramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conferencia', models.DateField(verbose_name='Data da Conferência')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('fiscal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conferencias_ferramentas', to=settings.AUTH_USER_MODEL, verbose_name='Fiscal')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conferencias_ferramentas', to='obras.obra', verbose_name='Obra')),
            ],
            options={
                'verbose_name': 'Conferência de Ferramenta',
                'verbose_name_plural': 'Conferências de Ferramentas',
                'ordering': ['-data_conferencia'],
                'unique_together': {('obra', 'data_conferencia')},
            },
        ),
        migrations.CreateModel(
            name='Ferramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('categoria', models.CharField(choices=[('manual', 'Ferramenta Manual'), ('eletrica', 'Ferramenta Elétrica'), ('medicao', 'Instrumento de Medição'), ('seguranca', 'EPI/Segurança'), ('outros', 'Outros')], max_length=20, verbose_name='Categoria')),
                ('status', models.CharField(choices=[('deposito', 'No Depósito'), ('em_obra', 'Em Obra'), ('manutencao', 'Em Manutenção'), ('perdida', 'Perdida'), ('descartada', 'Descartada')], default='deposito', max_length=20, verbose_name='Status')),
                ('data_aquisicao', models.DateField(blank=True, null=True, verbose_name='Data de Aquisição')),
                ('valor_aquisicao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor de Aquisição (R$)')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='ferramentas/fotos/', verbose_name='Foto')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('obra_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ferramentas_alocadas', to='obras.obra', verbose_name='Obra Atual')),
            ],
            options={
                'verbose_name': 'Ferramenta',
                'verbose_name_plural': 'Ferramentas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoFerramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Movimentação')),
                ('tipo', models.CharField(choices=[('entrada_deposito', 'Entrada no Depósito'), ('saida_obra', 'Saída para Obra'), ('transferencia', 'Transferência entre Obras'), ('retorno_deposito', 'Retorno ao Depósito'), ('manutencao', 'Envio para Manutenção'), ('retorno_manutencao', 'Retorno de Manutenção'), ('perda', 'Perda/Extravio'), ('descarte', 'Descarte')], max_length=20, verbose_name='Tipo de Movimentação')),
                ('origem', models.CharField(blank=True, max_length=200, null=True, verbose_name='Origem')),
                ('destino', models.CharField(blank=True, max_length=200, null=True, verbose_name='Destino')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('ferramenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='ferramentas.ferramenta', verbose_name='Ferramenta')),
                ('obra_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_entrada', to='obras.obra', verbose_name='Obra Destino')),
                ('obra_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_saida', to='obras.obra', verbose_name='Obra Origem')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_ferramenta', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Movimentação de Ferramenta',
                'verbose_name_plural': 'Movimentações de Ferramentas',
                'ordering': ['-data_movimentacao'],
            },
        ),
        migrations.CreateModel(
            name='ItemConferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ok', 'OK - Presente'), ('ausente', 'Ausente'), ('danificada', 'Danificada')], max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('conferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='ferramentas.conferenciaferramenta', verbose_name='Conferência')),
                ('ferramenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conferencias', to='ferramentas.ferramenta', verbose_name='Ferramenta')),
            ],
            options={
                'verbose_name': 'Item de Conferência',
                'verbose_name_plural': 'Itens de Conferência',
                'unique_together': {('conferencia', 'ferramenta')},
            },
        ),
    ]
