# Generated by Django 5.0.1 on 2026-02-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenciaferramenta',
            name='data_conferencia',
            field=models.DateTimeField(verbose_name='Data e Hora da Conferência'),
        ),
    ]
