# Generated by Django 5.0.1 on 2026-02-16 20:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentas', '0002_alter_conferenciaferramenta_data_conferencia'),
        ('obras', '0008_etapahistorico'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conferenciaferramenta',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='ferramenta',
            name='obra_atual',
        ),
        migrations.RemoveField(
            model_name='ferramenta',
            name='status',
        ),
        migrations.RemoveField(
            model_name='ferramenta',
            name='valor_aquisicao',
        ),
        migrations.RemoveField(
            model_name='movimentacaoferramenta',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='movimentacaoferramenta',
            name='origem',
        ),
        migrations.AddField(
            model_name='conferenciaferramenta',
            name='observacoes_gerais',
            field=models.TextField(blank=True, null=True, verbose_name='Observações Gerais'),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='quantidade_total',
            field=models.IntegerField(default=0, help_text='Total de unidades existentes (soma de todas localizações)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade Total no Estoque'),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='valor_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço de uma unidade', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Unitário (R$)'),
        ),
        migrations.AddField(
            model_name='itemconferencia',
            name='quantidade_encontrada',
            field=models.IntegerField(default=0, help_text='Quantidade realmente encontrada na conferência', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade Encontrada'),
        ),
        migrations.AddField(
            model_name='itemconferencia',
            name='quantidade_esperada',
            field=models.IntegerField(default=0, help_text='Quantidade que deveria estar na obra segundo o sistema', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade Esperada'),
        ),
        migrations.AddField(
            model_name='movimentacaoferramenta',
            name='destino_tipo',
            field=models.CharField(blank=True, max_length=20, verbose_name='Tipo de Destino'),
        ),
        migrations.AddField(
            model_name='movimentacaoferramenta',
            name='origem_tipo',
            field=models.CharField(blank=True, max_length=20, verbose_name='Tipo de Origem'),
        ),
        migrations.AddField(
            model_name='movimentacaoferramenta',
            name='quantidade',
            field=models.IntegerField(default=1, help_text='Quantas unidades estão sendo movimentadas', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Ferramentas inativas não aparecem nas listagens', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='data_aquisicao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Primeira Aquisição'),
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='ferramentas/fotos/', verbose_name='Foto do Modelo'),
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome do Modelo'),
        ),
        migrations.AlterField(
            model_name='itemconferencia',
            name='status',
            field=models.CharField(choices=[('ok', 'OK - Bate'), ('falta', 'Falta'), ('sobra', 'Sobra')], default='ok', help_text='Calculado automaticamente', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='movimentacaoferramenta',
            name='obra_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_entrada_ferramenta', to='obras.obra', verbose_name='Obra Destino'),
        ),
        migrations.AlterField(
            model_name='movimentacaoferramenta',
            name='obra_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_saida_ferramenta', to='obras.obra', verbose_name='Obra Origem'),
        ),
        migrations.AlterField(
            model_name='movimentacaoferramenta',
            name='tipo',
            field=models.CharField(choices=[('entrada_deposito', 'Entrada no Depósito (Compra/Recebimento)'), ('saida_obra', 'Saída para Obra'), ('transferencia', 'Transferência entre Obras'), ('retorno_deposito', 'Retorno ao Depósito'), ('envio_manutencao', 'Envio para Manutenção'), ('retorno_manutencao', 'Retorno de Manutenção'), ('perda', 'Perda/Extravio'), ('descarte', 'Descarte/Baixa')], max_length=20, verbose_name='Tipo de Movimentação'),
        ),
        migrations.CreateModel(
            name='LocalizacaoFerramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_tipo', models.CharField(choices=[('deposito', 'Depósito'), ('obra', 'Em Obra'), ('manutencao', 'Manutenção'), ('perdida', 'Perdida/Extraviada')], max_length=20, verbose_name='Tipo de Local')),
                ('quantidade', models.IntegerField(help_text='Quantas unidades estão neste local', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ferramenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localizacoes', to='ferramentas.ferramenta', verbose_name='Ferramenta')),
                ('obra', models.ForeignKey(blank=True, help_text="Obrigatório apenas se local_tipo='obra'", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ferramentas_localizadas', to='obras.obra', verbose_name='Obra')),
            ],
            options={
                'verbose_name': 'Localização de Ferramenta',
                'verbose_name_plural': 'Localizações de Ferramentas',
            },
        ),
        migrations.AddConstraint(
            model_name='localizacaoferramenta',
            constraint=models.UniqueConstraint(condition=models.Q(('obra__isnull', True)), fields=('ferramenta', 'local_tipo'), name='unique_ferramenta_local_nao_obra'),
        ),
        migrations.AddConstraint(
            model_name='localizacaoferramenta',
            constraint=models.UniqueConstraint(condition=models.Q(('local_tipo', 'obra')), fields=('ferramenta', 'obra'), name='unique_ferramenta_obra'),
        ),
    ]
