# Generated by Django 5.0.1 on 2026-02-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentas', '0003_alter_conferenciaferramenta_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ferramenta',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Define se a ferramenta está ativa; itens inativos podem ser exibidos via filtro na listagem', verbose_name='Ativo'),
        ),
    ]
